development:
  adapter: postgresql
  host: 127.0.0.1
  port: 5432
  username: geostaff
  database: geoserver
  schema_search_path: druid,public
  pool: 5
  timeout: 5000

testing:
  adapter: postgresql
  host: 127.0.0.1
  port: 5432
  username: geostaff
  database: geoserver
  schema_search_path: druid,public
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  host: 127.0.0.1
  port: 5432
  username: geostaff
  database: geoserver
  schema_search_path: druid,public
  pool: 5
  timeout: 5000